default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  prepared_statements: false
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] %>
  timeout: 5000
  database: quote
  username: postgres
  password: postgres

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: quote_test
  pool: 5

